name: commodity_forecasting2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - ipykernel
  - pip
  - pip:
    - lightning==2.3.3
    - wandb==0.17.4
    - pandas==2.2.2
